# Use official PHP + Apache image
FROM php:8.2-apache

# Install required libs + PHP MySQL extensions
RUN apt-get update && apt-get install -y \
    curl \
    libssl-dev \
    && docker-php-ext-install mysqli pdo pdo_mysql

# Download AWS RDS CA bundle for secure MySQL SSL
RUN mkdir -p /opt/rds-ca \
    && curl -o /opt/rds-ca/global-bundle.pem https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem \
    && chmod 644 /opt/rds-ca/global-bundle.pem

# Copy application code
COPY . /var/www/html/

# Permissions
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

# Expose port 80
EXPOSE 80

# Start Apache
CMD ["apache2-foreground"]
